import Foundation
import XCTest

@testable import SymMeetCore

/// Golden fixture-compare tests for every `symmeet export` format. Fixtures
/// live under `Tests/Fixtures/exports/` and were generated by rendering the
/// scenarios below once and hand-verifying the output, then committing it as
/// the regression baseline (the standard golden-test workflow).
///
/// Two scenarios cover every edge case called out in issue #11:
///
/// - `kitchenSink`: overlapping speakers (segments 1 and 2 share time
///   range), Unicode text (accented Latin), right-to-left text (Arabic),
///   an anonymous/generic speaker label (`speaker_unknown`), an hour-plus
///   timestamp (segment 4 starts after 3,661,000 ms), and a long utterance
///   that forces SRT/VTT line-wrapping. Segments are deliberately
///   constructed out of chronological order to prove `json`/`jsonl` preserve
///   evidentiary (store-read) order while `markdown`/`txt`/`srt`/`vtt`
///   re-sort chronologically for human/subtitle consumption.
/// - `silence`: a completed meeting with zero segments, exercising every
///   renderer's empty-transcript path.
final class ExportGoldenTests: XCTestCase {

  // MARK: - Scenarios

  fileprivate static let kitchenSinkMeetingID = UUID(
    uuidString: "11111111-1111-1111-1111-111111111111")!
  fileprivate static let silenceMeetingID = UUID(
    uuidString: "22222222-2222-2222-2222-222222222222")!

  fileprivate static func kitchenSinkManifest() -> MeetingManifest {
    MeetingManifest(
      meetingID: kitchenSinkMeetingID,
      source: .imported,
      createdAt: Date(timeIntervalSince1970: 1_700_000_000),
      updatedAt: Date(timeIntervalSince1970: 1_700_000_100),
      language: "multi",
      job: MeetingJob(
        jobID: UUID(uuidString: "99999999-9999-9999-9999-999999999999")!,
        state: .completed,
        engine: EngineProvenance(engineID: "test-engine", modelID: "tiny", modelVersion: "v1")),
      consent: ConsentState(status: .authorized),
      retention: RetentionMetadata(policy: .keep)
    )
  }

  /// Segments intentionally out of chronological order (`s2`, `s4`, `s1`,
  /// `s3`) to distinguish evidentiary order (json/jsonl) from re-sorted
  /// chronological order (markdown/txt/srt/vtt).
  fileprivate static func kitchenSinkSegments() -> [Segment] {
    let trackA = UUID(uuidString: "aaaaaaaa-0000-0000-0000-00000000000a")!
    let trackB = UUID(uuidString: "bbbbbbbb-0000-0000-0000-00000000000b")!

    let s1 = try! Segment(
      segmentID: UUID(uuidString: "aaaaaaaa-1111-1111-1111-111111111111")!,
      trackID: trackA,
      speakerID: "speaker_1",
      startMS: 0,
      endMS: 2_500,
      engineText: "Hello, world! Café — naïve résumé.")

    // Overlaps s1 (starts before s1 ends): different speaker, different
    // track, must remain its own cue rather than being merged or reordered.
    let s2 = try! Segment(
      segmentID: UUID(uuidString: "aaaaaaaa-2222-2222-2222-222222222222")!,
      trackID: trackB,
      speakerID: "speaker_2",
      startMS: 2_000,
      endMS: 4_000,
      engineText: "مرحبا بكم في الاجتماع")

    // Anonymous/unidentified speaker -- the "missing speaker label" edge
    // case within the Segment contract's own constraints (speaker_id can
    // never be nil or empty, only generic).
    let s3 = try! Segment(
      segmentID: UUID(uuidString: "aaaaaaaa-3333-3333-3333-333333333333")!,
      trackID: trackA,
      speakerID: "speaker_unknown",
      startMS: 4_000,
      endMS: 6_000,
      engineText:
        "Continuing without an identified speaker in this recording, to make sure anonymous participants still render clearly.",
      editedText: "Continuing without an identified speaker, edited for clarity.",
      revision: .userCorrected)

    // Hour-plus timestamp.
    let s4 = try! Segment(
      segmentID: UUID(uuidString: "aaaaaaaa-4444-4444-4444-444444444444")!,
      trackID: trackA,
      speakerID: "speaker_1",
      startMS: 3_661_000,
      endMS: 3_665_500,
      engineText:
        "Wrapping up after a long meeting that has run past the one hour mark, just to be sure our timestamp formatting handles it correctly."
    )

    return [s2, s4, s1, s3]
  }

  fileprivate static func silenceManifest() -> MeetingManifest {
    MeetingManifest(
      meetingID: silenceMeetingID,
      source: .imported,
      createdAt: Date(timeIntervalSince1970: 1_700_000_000),
      updatedAt: Date(timeIntervalSince1970: 1_700_000_100),
      job: MeetingJob(
        jobID: UUID(uuidString: "88888888-8888-8888-8888-888888888888")!,
        state: .completed,
        engine: EngineProvenance(engineID: "test-engine", modelID: "tiny", modelVersion: "v1")),
      consent: ConsentState(status: .authorized),
      retention: RetentionMetadata(policy: .keep)
    )
  }

  // MARK: - Golden comparisons: kitchen sink

  func testKitchenSinkMarkdownMatchesGoldenFixture() throws {
    let markdown = MarkdownRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments())
    XCTAssertEqual(markdown, try fixture("kitchen-sink", "md"))
  }

  func testKitchenSinkTextMatchesGoldenFixture() throws {
    let text = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .txt)
    XCTAssertEqual(text, try fixture("kitchen-sink", "txt"))
  }

  func testKitchenSinkTextWithTimestampsMatchesGoldenFixture() throws {
    let text = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .txt,
      options: TranscriptRenderer.Options(withTimestamps: true))
    XCTAssertEqual(text, try fixture("kitchen-sink.with-timestamps", "txt"))
  }

  func testKitchenSinkJSONMatchesGoldenFixture() throws {
    let json = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .json)
    XCTAssertEqual(json, try fixture("kitchen-sink", "json"))
  }

  func testKitchenSinkJSONLMatchesGoldenFixture() throws {
    let jsonl = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .jsonl)
    XCTAssertEqual(jsonl, try fixture("kitchen-sink", "jsonl"))
  }

  func testKitchenSinkSRTMatchesGoldenFixture() throws {
    let srt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .srt)
    XCTAssertEqual(srt, try fixture("kitchen-sink", "srt"))
  }

  func testKitchenSinkVTTMatchesGoldenFixture() throws {
    let vtt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .vtt)
    XCTAssertEqual(vtt, try fixture("kitchen-sink", "vtt"))
  }

  // MARK: - Golden comparisons: silence (zero segments)

  func testSilenceMarkdownMatchesGoldenFixture() throws {
    let markdown = MarkdownRenderer.render(manifest: Self.silenceManifest(), segments: [])
    XCTAssertEqual(markdown, try fixture("silence", "md"))
  }

  func testSilenceTextMatchesGoldenFixture() throws {
    let text = try TranscriptRenderer.render(
      manifest: Self.silenceManifest(), segments: [], segmentSource: .raw, format: .txt)
    XCTAssertEqual(text, try fixture("silence", "txt"))
    XCTAssertEqual(text, "")
  }

  func testSilenceJSONMatchesGoldenFixture() throws {
    let json = try TranscriptRenderer.render(
      manifest: Self.silenceManifest(), segments: [], segmentSource: .raw, format: .json)
    XCTAssertEqual(json, try fixture("silence", "json"))
  }

  func testSilenceJSONLIsEmpty() throws {
    let jsonl = try TranscriptRenderer.render(
      manifest: Self.silenceManifest(), segments: [], segmentSource: .raw, format: .jsonl)
    XCTAssertEqual(jsonl, "")
  }

  func testSilenceSRTIsEmpty() throws {
    let srt = try TranscriptRenderer.render(
      manifest: Self.silenceManifest(), segments: [], segmentSource: .raw, format: .srt)
    XCTAssertEqual(srt, "")
  }

  func testSilenceVTTHasHeaderOnly() throws {
    let vtt = try TranscriptRenderer.render(
      manifest: Self.silenceManifest(), segments: [], segmentSource: .raw, format: .vtt)
    XCTAssertEqual(vtt, "WEBVTT\n")
  }

  // MARK: - Ordering: json/jsonl preserve evidentiary order, others re-sort

  func testJSONLPreservesEvidentiaryOrderNotChronologicalOrder() throws {
    let segments = Self.kitchenSinkSegments()
    let jsonl = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: segments, segmentSource: .raw,
      format: .jsonl)
    let decoded = try jsonl.split(separator: "\n").map {
      try ContractCodec.decoder().decode(Segment.self, from: Data($0.utf8))
    }
    XCTAssertEqual(decoded.map(\.segmentID), segments.map(\.segmentID))
  }

  func testMarkdownTranscriptIsChronologicallySorted() throws {
    let markdown = MarkdownRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments())
    let firstIndex = try XCTUnwrap(markdown.range(of: "speaker_1"))
    let secondIndex = try XCTUnwrap(
      markdown.range(of: "speaker_2", range: firstIndex.upperBound..<markdown.endIndex))
    let unknownIndex = try XCTUnwrap(
      markdown.range(of: "speaker_unknown", range: secondIndex.upperBound..<markdown.endIndex))
    XCTAssertTrue(firstIndex.lowerBound < secondIndex.lowerBound)
    XCTAssertTrue(secondIndex.lowerBound < unknownIndex.lowerBound)
  }

  // MARK: - Determinism: identical inputs render byte-identical output

  func testRenderingIsDeterministicAcrossRepeatedCalls() throws {
    for format in ExportFormat.allCases {
      let first = try TranscriptRenderer.render(
        manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
        segmentSource: .raw, format: format)
      let second = try TranscriptRenderer.render(
        manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
        segmentSource: .raw, format: format)
      XCTAssertEqual(first, second, "\(format.rawValue) must render byte-identical output twice")
    }
  }

  // MARK: - Unicode / RTL round-trip fidelity

  func testUnicodeAndRTLTextRoundTripsThroughJSONL() throws {
    let jsonl = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .jsonl)
    XCTAssertTrue(jsonl.contains("Café — naïve résumé"))
    XCTAssertTrue(jsonl.contains("مرحبا بكم في الاجتماع"))

    let decoded = try jsonl.split(separator: "\n").map {
      try ContractCodec.decoder().decode(Segment.self, from: Data($0.utf8))
    }
    // speaker_1 appears twice in this scenario (segments 1 and 4), so look
    // each segment up by its unique ID rather than by speaker.
    let latinSegmentID = UUID(uuidString: "aaaaaaaa-1111-1111-1111-111111111111")!
    let rtlSegmentID = UUID(uuidString: "aaaaaaaa-2222-2222-2222-222222222222")!
    XCTAssertEqual(
      decoded.first { $0.segmentID == latinSegmentID }?.engineText,
      "Hello, world! Café — naïve résumé.")
    XCTAssertEqual(
      decoded.first { $0.segmentID == rtlSegmentID }?.engineText, "مرحبا بكم في الاجتماع")
  }

  func testUnicodeAndRTLTextRoundTripsThroughJSON() throws {
    let json = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .json)
    XCTAssertTrue(json.contains("Café — naïve résumé"))
    XCTAssertTrue(json.contains("مرحبا بكم في الاجتماع"))
  }

  func testUnicodeAndRTLTextAppearVerbatimInMarkdownAndTxtAndSubtitles() throws {
    for format: ExportFormat in [.markdown, .txt, .srt, .vtt] {
      let content = try TranscriptRenderer.render(
        manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
        segmentSource: .raw, format: format)
      // srt/vtt word-wrap long cues onto multiple lines, which can insert a
      // newline at a word boundary inside a longer phrase (by design -- see
      // SubtitleRenderer's line-width rule). Collapse wrap-inserted newlines
      // back to spaces before the substring check so this test verifies text
      // fidelity, not line-breaking.
      let unwrapped = content.replacingOccurrences(of: "\n", with: " ")
      XCTAssertTrue(
        unwrapped.contains("Café — naïve résumé"),
        "\(format.rawValue) must preserve accented Latin text")
      XCTAssertTrue(
        unwrapped.contains("مرحبا بكم في الاجتماع"), "\(format.rawValue) must preserve RTL text")
    }
  }

  // MARK: - Edited-text preference

  func testDisplayTextPrefersEditedOverEngineText() throws {
    let text = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .txt)
    XCTAssertTrue(text.contains("edited for clarity"))
    XCTAssertFalse(text.contains("to make sure anonymous participants still render clearly"))
  }

  // MARK: - SRT/VTT structural validation

  func testKitchenSinkSRTValidatesCleanly() throws {
    let srt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .srt)
    try SubtitleValidator.validateSRT(srt)
  }

  func testKitchenSinkVTTValidatesCleanly() throws {
    let vtt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .vtt)
    try SubtitleValidator.validateVTT(vtt)
  }

  func testSubtitleLinesAreWrappedToPracticalWidth() throws {
    let srt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .srt)
    for line in srt.split(separator: "\n", omittingEmptySubsequences: false) {
      XCTAssertLessThanOrEqual(line.count, 42, "SRT line exceeds practical width: \(line)")
    }
  }

  func testOverlappingSpeakersRemainSeparateCues() throws {
    let srt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .srt)
    let cues = try SubtitleValidator.parseSRT(srt)
    // s1 (0-2500ms) and s2 (2000-4000ms) overlap; both must appear as their
    // own cue with an explicit speaker label rather than being merged.
    XCTAssertTrue(cues.contains { $0.text.contains("speaker_1:") })
    XCTAssertTrue(cues.contains { $0.text.contains("speaker_2:") })
    XCTAssertEqual(cues.count, 4)
  }

  func testHourPlusTimestampFormatsCorrectly() throws {
    let srt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .srt)
    XCTAssertTrue(srt.contains("01:01:01,000"))
    let vtt = try TranscriptRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments(),
      segmentSource: .raw, format: .vtt)
    XCTAssertTrue(vtt.contains("01:01:01.000"))
  }

  // MARK: - Markdown round-trip through MarkdownProjection's own contract
  //
  // MarkdownProjection (Sources/SymMeetCore/Contracts/MarkdownProjection.swift)
  // has no `decode` -- it is a one-way projection with a stable init/template,
  // not a Codable contract. So "round-trips through its own decode/encode" is
  // demonstrated here as: parse the rendered markdown's five stable sections
  // back out, feed them into a *fresh* `MarkdownProjection.init` (the
  // contract's own "encode" step), and confirm that produces byte-identical
  // markdown. This proves the template is information-preserving and stable
  // under the only reconstruction path the contract actually exposes.
  func testMarkdownRoundTripsThroughMarkdownProjectionContract() throws {
    let rendered = MarkdownRenderer.render(
      manifest: Self.kitchenSinkManifest(), segments: Self.kitchenSinkSegments())
    let parsed = try parseMarkdownProjectionSections(rendered)

    let rebuilt = MarkdownProjection(
      summary: parsed.summary,
      decisions: parsed.decisions,
      actionItems: parsed.actionItems,
      participants: parsed.participants,
      transcript: parsed.transcript)

    XCTAssertEqual(rebuilt.markdown, rendered)
    XCTAssertEqual(parsed.participants, ["speaker_1", "speaker_2", "speaker_unknown"])
  }

  // MARK: - Fixture loading

  private func fixture(_ name: String, _ ext: String) throws -> String {
    guard
      let url = Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "exports")
    else {
      XCTFail("Missing fixture: \(name).\(ext)")
      return ""
    }
    return String(decoding: try Data(contentsOf: url), as: UTF8.self)
  }
}

// MARK: - Markdown section parser (test-only, mirrors MarkdownProjection's own template)

private struct ParsedMarkdownSections {
  let summary: String
  let decisions: [String]
  let actionItems: [String]
  let participants: [String]
  let transcript: String
}

private func parseMarkdownProjectionSections(_ markdown: String) throws -> ParsedMarkdownSections {
  func section(_ heading: String, upTo nextHeading: String?, in text: String) throws -> String {
    let headingMarker = "## \(heading)\n\n"
    guard let start = text.range(of: headingMarker) else {
      throw ExportError.invalidOutputPath("missing heading \(heading)")
    }
    let afterHeading = start.upperBound
    if let nextHeading,
      let end = text.range(of: "\n\n## \(nextHeading)\n\n", range: afterHeading..<text.endIndex)
    {
      return String(text[afterHeading..<end.lowerBound])
    }
    return String(text[afterHeading...])
  }

  func parseList(_ block: String) -> [String] {
    if block == "- None" { return [] }
    return block.split(separator: "\n").map { String($0.dropFirst(2)) }
  }

  let summary = try section("Summary", upTo: "Decisions", in: markdown)
  let decisions = parseList(try section("Decisions", upTo: "Action Items", in: markdown))
  let actionItems = parseList(try section("Action Items", upTo: "Participants", in: markdown))
  let participants = parseList(try section("Participants", upTo: "Transcript", in: markdown))
  let transcript = try section("Transcript", upTo: nil, in: markdown)

  return ParsedMarkdownSections(
    summary: summary, decisions: decisions, actionItems: actionItems, participants: participants,
    transcript: transcript)
}

// MARK: - A small in-repo SRT/VTT validator (acceptance criterion #2)

enum SubtitleValidator {
  struct Cue {
    let index: Int?
    let startMS: Int
    let endMS: Int
    let text: String
  }

  private static let srtTimestamp = try! NSRegularExpression(
    pattern: #"^(\d{2,}):(\d{2}):(\d{2}),(\d{3})$"#)
  private static let vttTimestamp = try! NSRegularExpression(
    pattern: #"^(\d{2,}):(\d{2}):(\d{2})\.(\d{3})$"#)

  enum ValidationError: Error, CustomStringConvertible {
    case malformedBlock(String)
    case badTimestampFormat(String)
    case nonMonotonicStart(previous: Int, next: Int)
    case endNotAfterStart(start: Int, end: Int)
    case negativeTimestamp(Int)
    case missingHeader
    case badCueNumbering(expected: Int, found: Int)

    var description: String {
      switch self {
      case .malformedBlock(let block): "Malformed cue block: \(block)"
      case .badTimestampFormat(let value): "Timestamp does not match required format: \(value)"
      case .nonMonotonicStart(let previous, let next):
        "Cue start time went backward: \(previous) -> \(next)"
      case .endNotAfterStart(let start, let end): "Cue end (\(end)) is not after start (\(start))"
      case .negativeTimestamp(let value): "Negative timestamp: \(value)"
      case .missingHeader: "VTT file is missing its WEBVTT header"
      case .badCueNumbering(let expected, let found):
        "SRT cue numbering is not sequential: expected \(expected), found \(found)"
      }
    }
  }

  @discardableResult
  static func validateSRT(_ content: String) throws -> [Cue] {
    let cues = try parseSRT(content)
    try validateMonotonic(cues)
    return cues
  }

  @discardableResult
  static func validateVTT(_ content: String) throws -> [Cue] {
    guard content.hasPrefix("WEBVTT") else { throw ValidationError.missingHeader }
    let cues = try parseVTT(content)
    try validateMonotonic(cues)
    return cues
  }

  private static func validateMonotonic(_ cues: [Cue]) throws {
    var previousStart = -1
    for cue in cues {
      guard cue.startMS >= 0, cue.endMS >= 0 else {
        throw ValidationError.negativeTimestamp(min(cue.startMS, cue.endMS))
      }
      guard cue.endMS > cue.startMS else {
        throw ValidationError.endNotAfterStart(start: cue.startMS, end: cue.endMS)
      }
      guard cue.startMS >= previousStart else {
        throw ValidationError.nonMonotonicStart(previous: previousStart, next: cue.startMS)
      }
      previousStart = cue.startMS
    }
  }

  static func parseSRT(_ content: String) throws -> [Cue] {
    guard !content.isEmpty else { return [] }
    let blocks = content.components(separatedBy: "\n\n").filter { !$0.isEmpty }
    var cues: [Cue] = []
    var expectedIndex = 1
    for block in blocks {
      let lines = block.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
      guard lines.count >= 2, let index = Int(lines[0]) else {
        throw ValidationError.malformedBlock(block)
      }
      guard index == expectedIndex else {
        throw ValidationError.badCueNumbering(expected: expectedIndex, found: index)
      }
      expectedIndex += 1
      let (start, end) = try parseRange(lines[1], regex: srtTimestamp)
      let text = lines[2...].joined(separator: "\n")
      cues.append(Cue(index: index, startMS: start, endMS: end, text: text))
    }
    return cues
  }

  static func parseVTT(_ content: String) throws -> [Cue] {
    var blocks = content.components(separatedBy: "\n\n").filter { !$0.isEmpty }
    guard !blocks.isEmpty else { return [] }
    if blocks[0].trimmingCharacters(in: .whitespacesAndNewlines) == "WEBVTT" {
      blocks.removeFirst()
    }
    var cues: [Cue] = []
    for block in blocks {
      let lines = block.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
      guard lines.count >= 2 else { throw ValidationError.malformedBlock(block) }
      let (start, end) = try parseRange(lines[0], regex: vttTimestamp)
      let text = lines[1...].joined(separator: "\n")
      cues.append(Cue(index: nil, startMS: start, endMS: end, text: text))
    }
    return cues
  }

  private static func parseRange(_ line: String, regex: NSRegularExpression) throws -> (Int, Int) {
    let parts = line.components(separatedBy: " --> ")
    guard parts.count == 2 else { throw ValidationError.malformedBlock(line) }
    let start = try parseTimestamp(parts[0], regex: regex)
    let end = try parseTimestamp(parts[1], regex: regex)
    return (start, end)
  }

  private static func parseTimestamp(_ value: String, regex: NSRegularExpression) throws -> Int {
    let range = NSRange(value.startIndex..<value.endIndex, in: value)
    guard let match = regex.firstMatch(in: value, range: range), match.numberOfRanges == 5 else {
      throw ValidationError.badTimestampFormat(value)
    }
    func group(_ index: Int) -> Int {
      let r = Range(match.range(at: index), in: value)!
      return Int(value[r])!
    }
    let hours = group(1)
    let minutes = group(2)
    let seconds = group(3)
    let millis = group(4)
    return hours * 3_600_000 + minutes * 60_000 + seconds * 1_000 + millis
  }
}
